config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'dashboard#index'
  resources :devices
  resources :device_requests
  resources :patients
  resources :feeds
  resources :notifications
  resources :hospitals

  mount ActionCable.server => '/cable'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/device_request.rb
class DeviceRequest < ApplicationRecord
  belongs_to :device

  after_create :notify_dashboard

  scope :assigned, -> {where(is_assigne: true)}
  scope :not_assigned, -> {where(is_assigne: false)}

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "device_id", "id", "message", "updated_at"]
  end

 def notify_dashboard
  	channel_name = "device_request_channel_#{self.device.users.last.id}"
  	data = "new"
  	ActionCable.server.broadcast channel_name, data 
  end
  
end

app/controllers/device_requests_controller.rb
class DeviceRequestsController < ApplicationController

	def index
		@requests = DeviceRequest.where(device_id: current_user.devices).order(id: :desc).page params[:page]
	end

end

app/helpers/device_requests_helper.rb
module DeviceRequestsHelper
end

app/views/device_requests/index.html.erb
 <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Devices Request</h1>
  
</div>

 <div class="card shadow mb-4 mt-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Your Devices</h6>
      </div>
      <!-- Card Body -->
      <div class="card-body overflow-auto" >
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">Device Code</th>
                <th scope="col">Message</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              <%@requests.each do |r|%>
                <tr>
                  <td><%= r.device.code%></td>
                  <td><%= r.message%></td>
                  <td><% if r.is_assigne%>
                      Already Assigned
                    <%else%>
                      <%=link_to "Assign Patient",new_patient_path(request_id: r.id)%>
                    <%end%>
                    </td>
                </tr>
              <%end%>
            </tbody>
          </table>
          <div class="digg_pagination float-end">
            <%#= will_paginate @requests, :container => false %>
            <%= paginate @requests %>
          </div>
        </div>
      </div>
    </div>