config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'dashboard#index'
  resources :devices
  resources :device_requests
  resources :patients
  resources :feeds
  resources :notifications
  resources :hospitals

  mount ActionCable.server => '/cable'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/device.rb
class Device < ApplicationRecord
	has_many :user_devices
	has_many :users,  through: :user_devices
    has_many :patients
    has_many :device_patients
    has_one :device_info
    accepts_nested_attributes_for :device_info

	def self.ransackable_attributes(auth_object = nil)
		["code", "created_at", "id", "status", "updated_at"]
	end

    def to_s
        "#{code}"
    end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController

	before_action :find_device, only: [:edit,:show,:update]
	
	def index
		@device = current_user.devices.order(id: :desc).page params[:page]
	end

	def new
		@device = Device.new
	end


	def create
		
	end 

	def show

	end 

	def edit
		
	end

	def update
		@device.update(device_params)
		redirect_to devices_path
	end

	private

	def find_device
		@device = Device.find(params[:id])
	end

    def device_params
        params.require(:device).permit(:code,device_info_attributes: [:id,:mfg_date,:mode_name,:min_temperature, :max_temperature, :min_weight, :max_weight, :name ,setting: [:temperature,:weight]])
    end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/edit.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Devices Edit</h1>
  
</div>
<div class="card shadow mb-4 mt-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
      <h6 class="m-0 font-weight-bold text-primary">Your Devices</h6>
  </div>
  <!-- Card Body -->
  <div class="card-body overflow-auto" >
    <%= form_with(model: @device) do |form| %>
      <% if @device.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

          <ul>
            <% @device.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field mb-3">
        <%= form.label :code %>
        <%= form.text_field :code,read_only: true,class: "form-control form-control" %>
      </div>

      <%= form.fields_for :device_info do |info| %>
        <div class="field mb-3">
          <%= info.label :name %>
          <%= info.text_field :name,read_only: true,class: "form-control form-control" %>
        </div>
        <div class="field mb-3">
          <%= info.label :mode_name %>
          <%= info.text_field :mode_name,read_only: true,class: "form-control form-control" %>
        </div>

        <div class="field mb-3">
          <%= info.label :mfg_date %>
          <%= info.date_field :mfg_date,read_only: true,class: "form-control form-control" %>
        </div>
        <div class="mt-3">
          <div class="mb-3 row flex-row justify-content-between text-left">
            <div class="form-group col-sm-6 flex-column d-flex"> 
              <label class="form-control-label">
                Temperature min threshold
              </label> 
              <%= info.text_field :min_temperature,class: "form-control form-control" %>
            </div>

            <div class="form-group col-sm-6 flex-column d-flex"> 
              <label class="form-control-label">
                Temperature Max threshold
              </label> 
              <%= info.text_field :max_temperature,read_only: true,class: "form-control form-control" %>
            </div>
          </div>
          <div class="mb-3 row flex-row justify-content-between text-left">
            <div class="form-group col-sm-6 flex-column d-flex"> 
              <label class="form-control-label">
                Weight min threshold
              </label> 
              <%= info.text_field :min_weight,class: "form-control form-control" %>
            </div>

            <div class="form-group col-sm-6 flex-column d-flex"> 
              <label class="form-control-label">
                Weight max threshold
              </label> 
              <%= info.text_field :max_weight,read_only: true,class: "form-control form-control" %>
            </div>
          </div>
        </div>
      <%end%>

      <div class="actions">
        <%= form.submit 'Save device info', class: "btn btn-success mt-2 col-md-3 " %>
      </div>
    <% end %>
  </div>
</div>

app/views/devices/index.html.erb
 <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Devices</h1>
  
</div>

 <div class="card shadow mb-4 mt-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Your Devices</h6>
      </div>
      <!-- Card Body -->
      <div class="card-body overflow-auto" >
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">Code</th>
                <th scope="col">Name</th>
                <th scope="col">Hospital</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              <% @device.each do |device| %>
                <tr>
                  <td><%= device.code%></td>
                  <td><%=device.device_info.name %></td>
                  <td><%=current_user.hospital.name %></td>
                  <td><%= link_to "Edit",edit_device_path(device) %> | Show</td>
                </tr>
              <%end%>
            </tbody>
          </table>
          <div class="digg_pagination float-end">
            <%= paginate @device %>
          </div>
        </div>
      </div>
    </div>

app/views/devices/show.html.erb
 <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
  <h1 class="h2">Devices</h1>
  
</div>

 <div class="card shadow mb-4 mt-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
          <h6 class="m-0 font-weight-bold text-primary">Your Devices</h6>
      </div>
      <!-- Card Body -->
      <div class="card-body overflow-auto" >
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">Code</th>
                <th scope="col">Name</th>
                <th scope="col">Hospital</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            <tbody>
              <% @device.each do |device| %>
                <tr>
                  <td><%= device.code%></td>
                  <td><%=device.device_info.name %></td>
                  <td><%=current_user.hospital.name %></td>
                  <td><%= link_to "Edit",edit_device_path(device) %> | Show</td>
                </tr>
              <%end%>
            </tbody>
          </table>
          <div class="digg_pagination float-end">
            <%= will_paginate @device, :container => false %>
          </div>
        </div>
      </div>
    </div>